- project:
    templates:
      - openstack-python-jobs-horizon
      - openstack-python35-jobs-horizon
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
      - check-requirements
    check:
      jobs:
        - openstack-tox-lower-constraints
        - horizon-openstack-tox-python3-django111
    gate:
      jobs:
        - openstack-tox-lower-constraints
        - horizon-openstack-tox-python3-django111
